### ISSUE TITLE
About Motion In-betweening function

### ISSUE THREAD

**Issue by jackson09255921** [setarehc/diffusion-motion-inbetweening#9]
Hello @setarehc,

Your project is awesome to me. However, I have some questions about the motion in-betweening function.

My goal is to use the motion in-betweening function with my dataset, rather than inputting any text prompts. I want to select specific motion data from my dataset and generate a motion in-betweening .mp4 file.

However, I'm having trouble finding where to place my dataset and which commands to use.

Thank you so much!

**Comment by setarehc** [comment]
Hi @jackson09255921,

Thanks for your interest in our work.
 
You need to place your custom dataset under the folder `dataset/custome_dataset`. Then, you need to train our diffusion model on your dataset using `train.train_condmdi`. To be able to work with your dataset, you need to write a new dataset class. We have done this for the amass dataset which you can use for reference. Note that the data representation should be global if you want to define sparse keyframes. You also need to make modifications to the input dimensions of the model so that it supports the dimensions of your dataset.

Best,
Setareh
